# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

format = """
$cmd_duration $directory$git_branch
  $character"""

[fill]
symbol = '-'
style = 'fg:245'

[character]
success_symbol = "[](bold white)"
error_symbol = "[](bold white)"

[git_branch]
style = "white"
symbol = "󰘬"
format = " on [$symbol $branch]($style)"

[directory]
style = "bold white"
format = "[$path]($style)"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = " taken [$duration](bold white)"
