background            #000000
foreground            #d0d0d0
cursor                #ffffff
selection_background  #262626
selection_foreground  #ffffff

# Black
color0  #000000
color8  #111111

# Red (using grey)
color1  #333333
color9  #444444

# Green (using grey)
color2  #555555
color10 #666666

# Yellow (using grey)
color3  #777777
color11 #888888

# Blue (using grey)
color4  #999999
color12 #aaaaaa

# Magenta (using grey)
color5  #bbbbbb
color13 #cccccc

# Cyan (using grey)
color6  #dddddd
color14 #eeeeee

# White
color7  #ffffff
color15 #ffffff
